# Generated by Django 4.2.2 on 2023-06-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CSVSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("reviews", models.URLField(blank=True, null=True)),
                ("text_reviews", models.TextField(blank=True, null=True)),
                (
                    "review_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "reviews_username",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("weight", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
