# Generated by Django 4.2.2 on 2023-06-19 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productrating",
            options={"verbose_name": "Рейтинг", "verbose_name_plural": "Рейтинги"},
        ),
        migrations.AddField(
            model_name="productrating",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
