# Generated by Django 4.2.2 on 2023-06-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_productrating_options_productrating_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rate",
            field=models.FloatField(blank=True, null=True, verbose_name="рейтинг"),
        ),
        migrations.DeleteModel(
            name="ProductRating",
        ),
    ]
